services:
  serve:
    image: caddy:2.6.2-alpine
    volumes:
      - ./dist:/usr/share/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./public:/usr/share/caddy/
    ports:
      - 3000:80

  vite:
    image: node:18.11.0-alpine3.15
    working_dir: $PWD
    user: node
    init: true
    command: sh -c 'npm install && npx vite build --watch --sourcemap'
    volumes:
      - .:/$PWD

  static-build:
    image: node:18.11.0-alpine3.15
    working_dir: $PWD
    user: node
    init: true
    command: sh -c 'npm install && node --watch src/static-build/index.js'
    volumes:
      - .:/$PWD

  rss:
    image: node:18.11.0-alpine3.15
    working_dir: $PWD
    user: node
    init: true
    command: sh -c 'npm install && node --watch src/rss/index.js'
    volumes:
      - .:/$PWD
